<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '1#post|n>1#posts' => '',
  '1#topic|n>1#topics' => '',
  'Comment' => '',
  'Desired login name' => '',
  'Display Name (optional)' => '',
  'E-mail me the link' => '',
  'Enter your email, and a brand new login key will be sent to you. Click the link in the email to log in, and then change your password.' => '',
  'Enter your password again' => '',
  'Feed for this forum' => '',
  'Get a new code' => '',
  'Home' => '',
  'Identity Url' => '',
  'Last post' => '',
  'Latest post' => '',
  'Latest topics' => '',
  'Letters are not case-sensitive.' => '',
  'Login' => '',
  'Logins should start with least 2 characters and may consist of letters, numbers, or the underscore.' => '',
  'Member since' => '',
  'Name' => '',
  'No recent activity' => '',
  'Password (must be at least 5 characters)' => '',
  'Please enter the letters as they are shown in the image above.' => '',
  'Post your reply' => '',
  'Posts' => '',
  'Preview' => '',
  'Recent Posts' => '',
  'Recent posts' => '',
  'Remember me next time' => '',
  'Reset Password' => '',
  'Save Reply' => '',
  'Search' => '',
  'Sign up' => '',
  'Sign up!' => '',
  'Signup' => '',
  'Subscribe to' => '',
  'That username is already taken. Please try another one.' => '',
  'This is a topic in' => '',
  'Topic' => '',
  'Trouble Logging In?' => '',
  'Users' => '',
  'Verification Code' => '',
  'Views' => '',
  'Website' => '',
  'You need an account to post messages.' => '',
  'Your email address' => '',
  'by' => '',
  'cancel' => '',
  'if you don\'t have an account.' => '',
  'login' => '',
  'or' => '',
  'posts' => '',
  'reset password' => '',
  'to post a reply' => '',
  'to post a topic' => '',
  'topics' => '',
);
