<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '1#post|n>1#posts' => 'innlegg',
  '1#topic|n>1#topics' => 'emne',
  'E-mail me the link' => '',
  'Enter your email, and a brand new login key will be sent to you. Click the link in the email to log in, and then change your password.' => '',
  'Feed for this forum' => '',
  'Identity Url' => '',
  'Latest post' => '',
  'Logins should start with least 2 characters and may consist of letters, numbers, or the underscore.' => '',
  'Please enter the letters as they are shown in the image above.' => '',
  'Preview' => '',
  'Recent Posts' => '',
  'Recent posts' => '',
  'Save Reply' => '',
  'Sign up' => '',
  'Sign up!' => '',
  'if you don\'t have an account.' => '',
  'Comment' => 'Kommentar',
  'Desired login name' => 'Ønska brukarnamn',
  'Display Name (optional)' => 'Fullt namn (valfritt)',
  'Enter your password again' => 'Skriv inn passordet ditt ein gong til',
  'Get a new code' => 'Hent ein ny kode',
  'Home' => 'Heim',
  'Last post' => 'Siste innlegg',
  'Latest topics' => 'Siste emne',
  'Letters are not case-sensitive.' => 'Det er ikkje skilnad mellom store og små bokstavar.',
  'Login' => 'Logg inn',
  'Member since' => 'Medlem sidan',
  'Name' => 'Namn',
  'No recent activity' => 'Ingen aktivitet',
  'Password (must be at least 5 characters)' => 'Passord (må vere minst 5 teikn)',
  'Post your reply' => 'Skriv kommentaren din',
  'Posts' => 'Innlegg',
  'Remember me next time' => 'Hugs meg neste gong',
  'Reset Password' => 'Gløymd passord',
  'Search' => 'Søk',
  'Signup' => 'Bli medlem',
  'Subscribe to' => 'Abonner på',
  'That username is already taken. Please try another one.' => 'Brukarnamnet er allereie opptatt. Prøv eit annet.',
  'This is a topic in' => 'Dette er eit emne i',
  'Topic' => 'Emne',
  'Trouble Logging In?' => 'Problem med å logge inn?',
  'Users' => 'Brukarar',
  'Verification Code' => 'Verifiseringskode',
  'Views' => 'Visingar',
  'Website' => 'Heimeside',
  'You need an account to post messages.' => 'Du må vere medlem for å skrive eit innlegg',
  'Your email address' => 'E-postadressa di',
  'by' => 'av',
  'cancel' => 'avbryt',
  'login' => 'logg inn',
  'or' => 'eller',
  'posts' => 'innlegg',
  'reset password' => 'gløymd passord',
  'to post a reply' => 'for å svare på innlegget',
  'to post a topic' => 'for å skrive eit innlegg',
  'topics' => 'emne',
);
