<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '1#post|n>1#posts' => '1#innlegg|n>1#innlegg',
  '1#topic|n>1#topics' => '1#emne|n>1#emner',
  'Identity Url' => '',
  'Latest post' => 'Siste innlegg',
  'Preview' => 'Forhåndsvisning',
  'Recent Posts' => 'Siste innlegg',
  'Save Reply' => 'Svar',
  'Sign up' => 'Bli medlem',
  'Comment' => 'Innlegg',
  'Desired login name' => 'Ønsket brukernavn',
  'Display Name (optional)' => 'Fullt navn (valgfritt)',
  'E-mail me the link' => 'Send meg linken på e-post',
  'Enter your email, and a brand new login key will be sent to you. Click the link in the email to log in, and then change your password.' => 'Skriv inn din e-postadresse og vi sender deg nye detaljer for å logge inn på e-post. Klikk på linken i e-posten for å endre passordet ditt.',
  'Enter your password again' => 'Skriv inn passordet en gang til',
  'Feed for this forum' => 'Feed fra dette forumet',
  'Get a new code' => 'Hent ny kode',
  'Home' => 'Hjem',
  'Last post' => 'Siste innlegg',
  'Latest topics' => 'Siste emne(r)',
  'Letters are not case-sensitive.' => 'Bokstaver er ikke case-sensitive',
  'Login' => 'Logg inn',
  'Logins should start with least 2 characters and may consist of letters, numbers, or the underscore.' => 'Brukernavn bør starte med minst to tegn, og kan bestå av tall, bokstaver eller understrek.',
  'Member since' => 'Medlem siden',
  'Name' => 'Navn',
  'No recent activity' => 'Ingen aktivitet nylig',
  'Password (must be at least 5 characters)' => 'Passord (må bestå av minst fem tegn)',
  'Please enter the letters as they are shown in the image above.' => 'Vennligst skriv inn bokstavene slik de opptrer i bildet over',
  'Post your reply' => 'Skriv en kommentar',
  'Posts' => 'Innlegg',
  'Recent posts' => 'Siste innlegg',
  'Remember me next time' => 'Husk meg neste gang',
  'Reset Password' => 'Glemt passord',
  'Search' => 'Søk',
  'Sign up!' => 'Bli medlem!',
  'Signup' => 'Bli medlem',
  'Subscribe to' => 'Abonnér på',
  'That username is already taken. Please try another one.' => 'Det brukernavnet er allerede tatt. Vennligst prøv et annet.',
  'This is a topic in' => 'Dette er et emne i',
  'Topic' => 'Emne',
  'Trouble Logging In?' => 'Problemer med å logge inn?',
  'Users' => 'Brukere',
  'Verification Code' => 'Verifiseringskode',
  'Views' => 'Visninger',
  'Website' => 'Nettside',
  'You need an account to post messages.' => 'Du må være medlem for å skrive innlegg',
  'Your email address' => 'Din e-postadresse',
  'by' => 'av',
  'cancel' => 'avbryt',
  'if you don\'t have an account.' => 'hvis du ikke er medlem.',
  'login' => 'logg inn',
  'or' => 'eller',
  'posts' => 'innlegg',
  'reset password' => 'glemt passord',
  'to post a reply' => 'for å skrive en kommentar',
  'to post a topic' => 'for å starte et nytt emne',
  'topics' => 'emne(r)',
);
